### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-aroatdlt#1]
Really cool job @aroatdlt  !!!

Here you have some tips to improve the exercise:

- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input

- [x] Define the logic to generate and save the random number (remember we gave you a sample code)
- [x] Define the logic to make the counter work
- [x] Remember to convert input value string to a number
- [ ] Extract the feedback painter to a function
- [x] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement
- [x] Move variables and constants declaration to the top of the file
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] When writing a for, be careful with syntaxis because it can lead you to an infinite loop. Anyway, we don't need it for this exercise.

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by aroatdlt** [comment]
Hi @nasivuela ! I think that my evaluation is already ok. I should improve the style but maybe in holidays I will have enough time to do it! Please check it and if you find something to improve, tell me!
Thank you =)

**Comment by nasivuela** [comment]
Good Job @aroatdlt !!!

![](https://media.giphy.com/media/OcZp0maz6ALok/giphy.gif)

I'm closing this, but if you want more challenges:
- Notice you are writing 3 times `getTrack.innerHTML = 'something'`,  you could extract it to a function.
- What about adding a restart functionality when the game ends? :D
